package com.suhel.llamabro.sdk.model

/**
 * An accumulated snapshot of a response generated by the LLM.
 *
 * In a streaming context (e.g., [com.suhel.llamabro.sdk.LlamaChatSession.completion]),
 * this object is emitted multiple times. Each emission represents the state of the 
 * response at that point in time, with [contentText] and [thinkingText] containing 
 * all text generated so far.
 *
 * @property thinkingText The accumulated reasoning or "thinking" output from the model.
 *                        Commonly used with reasoning models that output `<think>` blocks.
 * @property contentText  The accumulated final response text.
 * @property tokensPerSecond The generation speed in tokens per second. Only populated when
 *                           [isComplete] is true.
 * @property isComplete   True if the model reached an End-of-Generation (EOG) token or a
 *                        stop sequence.
 * @property isInterrupted True if the generation was manually stopped via [com.suhel.llamabro.sdk.LlamaSession.abort]
 *                         or by cancelling the collection of the flow.
 */
data class Completion(
    val thinkingText: String? = null,
    val contentText: String? = null,
    val tokensPerSecond: Float? = null,
    val isComplete: Boolean = false,
    val isInterrupted: Boolean = false,
)
