package com.suhel.llamabro.sdk.model

/**
 * An accumulated snapshot of a response generated by the LLM.
 *
 * In a streaming context (e.g., [com.suhel.llamabro.sdk.LlamaChatSession.completion]),
 * this object is emitted multiple times. Each emission represents the state of the
 * response at that point in time, with [contentText] and [thinkingText] containing
 * all text generated so far.
 *
 * ### Terminal state
 * The final emission always has [isComplete] = true. Inspect [isInterrupted] and [result]
 * to determine how generation ended:
 *
 * | [isComplete] | [isInterrupted] | [result] | Meaning                                    |
 * |---|---|---|---|
 * | true         | false           | null    | Natural EOS or stop-string hit             |
 * | true         | true            | null    | Cancelled by user or context overflow      |
 * | true         | false           | non-null| Fatal error (decode failure, native crash) |
 *
 * The [com.suhel.llamabro.sdk.LlamaChatSession.completion] flow **never throws**;
 * all failure conditions are surfaced here so callers need only collect the flow.
 *
 * @property thinkingText     Accumulated reasoning text (inside `<think>...</think>` blocks).
 * @property contentText      Accumulated final response text.
 * @property tokensPerSecond  Generation speed. Only populated on the final emission.
 * @property isComplete       True on the last emission.
 * @property isInterrupted    True if generation was cut short by cancellation or overflow.
 * @property result            Non-null only for fatal errors (e.g. [LlamaError.DecodeFailed]).
 */
data class Completion(
    val thinkingText: String? = null,
    val contentText: String? = null,
    val tokensPerSecond: Float? = null,
    val isComplete: Boolean = false,
    val isInterrupted: Boolean = false,
    val error: LlamaError? = null,
)
