package com.suhel.llamabro.sdk.model

/**
 * Represents a single entry in the conversation history.
 */
sealed interface Message {
    val content: String

    /** A message sent by the human participant. */
    data class User(override val content: String) : Message

    /**
     * A message generated by the model.
     *
     * @param content         The main response text.
     * @param thinking        The model's internal reasoning (non-null only when the model
     *                        emits `<think>…</think>` blocks, e.g. reasoning models).
     * @param tokensPerSecond Generation speed in tokens per second. Null if the generation
     *                        was cancelled before completion, or if this message was added manually.
     */
    data class Assistant(
        override val content: String,
        val thinking: String? = null,
        val tokensPerSecond: Float? = null,
    ) : Message
}
