package com.suhel.llamabro.sdk.model

/**
 * Represents a single message in a conversation history.
 *
 * This sealed interface defines the two roles supported by the SDK: [User] and [Assistant].
 * These messages are used by [com.suhel.llamabro.sdk.LlamaChatSession.loadHistory] to 
 * restore state and are formatted according to the model's [PromptFormat].
 */
sealed interface Message {
    /** The textual content of the message. */
    val content: String

    /** 
     * A message sent by the human participant. 
     * 
     * @param content The raw text from the user.
     */
    data class User(override val content: String) : Message

    /**
     * A message generated by the AI model.
     *
     * @param content         The main response text generated by the model.
     * @param thinking        The model's internal reasoning process. This is only
     *                        populated for reasoning models (e.g., DeepSeek-R1)
     *                        that output `<think>...</think>` blocks.
     * @param tokensPerSecond The generation speed for this specific message.
     *                        Null if the message was restored from history.
     */
    data class Assistant(
        override val content: String,
        val thinking: String? = null,
        val tokensPerSecond: Float? = null,
    ) : Message
}
