package com.suhel.llamabro.sdk.chat

/**
 * Token usage statistics for a chat completion, mirroring the OpenAI usage object.
 *
 * @param promptTokens Number of tokens in the prompt (cached + newly ingested).
 * @param completionTokens Number of tokens generated by the model.
 * @param totalTokens Total tokens (prompt + completion).
 * @param tokensPerSecond Generation speed in tokens per second (SDK extension, not in OpenAI).
 */
data class Usage(
    val promptTokens: Int,
    val completionTokens: Int,
    val totalTokens: Int,
    val tokensPerSecond: Float,
)
